// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKWg44svOGCMD1uYfIB60hYXjZHUrtBHA',
    appId: '1:605364404859:web:ce5f28754691cbe38718de',
    messagingSenderId: '605364404859',
    projectId: 'civic24-17d66',
    authDomain: 'civic24-17d66.firebaseapp.com',
    storageBucket: 'civic24-17d66.appspot.com',
    measurementId: 'G-SXTYD8X1DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPc4N5PT44J1ey6lGez-h_SfS5eOaYScQ',
    appId: '1:605364404859:android:c4575abd5f68748f8718de',
    messagingSenderId: '605364404859',
    projectId: 'civic24-17d66',
    storageBucket: 'civic24-17d66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwo6cKZwVYgUK1tJI0env8PMBEea_uqqY',
    appId: '1:605364404859:ios:fbcc64b70b05802c8718de',
    messagingSenderId: '605364404859',
    projectId: 'civic24-17d66',
    storageBucket: 'civic24-17d66.appspot.com',
    iosBundleId: 'com.civic24.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwo6cKZwVYgUK1tJI0env8PMBEea_uqqY',
    appId: '1:605364404859:ios:07cd7995ff1584df8718de',
    messagingSenderId: '605364404859',
    projectId: 'civic24-17d66',
    storageBucket: 'civic24-17d66.appspot.com',
    iosBundleId: 'com.example.civic24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKWg44svOGCMD1uYfIB60hYXjZHUrtBHA',
    appId: '1:605364404859:web:7e4dfc268c47a2c18718de',
    messagingSenderId: '605364404859',
    projectId: 'civic24-17d66',
    authDomain: 'civic24-17d66.firebaseapp.com',
    storageBucket: 'civic24-17d66.appspot.com',
    measurementId: 'G-2TGLYL574Q',
  );
}
